import { Inter } from "next/font/google";
import "./globals.css";
// import { MantineProvider } from '@mantine/core';
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Home({ Component, pageProps }) {  // Ensure this is pageProps
  return (
    <>
      <div className={inter.className}>
        <Component {...pageProps} />  {/* Use pageProps here */}
      </div>
    </>
  );
}

export default Home;
